upstream my_backend {
    server 172.17.0.1:8080 weight=2;
    server 172.17.0.1:8081;
    server 172.17.0.1:8082;
}

server {
    listen 80;
    server_name _; # Слушаем всё

    location / {
        proxy_pass http://my_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
